# Generated by Django 4.1.5 on 2023-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('region', models.CharField(choices=[('E', 'East'), ('W', 'West'), ('N', 'North'), ('S', 'South')], max_length=1)),
                ('city', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('B', 'Bars'), ('C', 'Cookies'), ('CR', 'Crackers')], max_length=2)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
